/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Palette exacte du modèle "Élégance Célébration"
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#4b463c',
        'error': '#ba1a1a',
        'tertiary-fixed-dim': '#c8c6c5',
        'tertiary-fixed': '#e4e2e1',
        'surface-bright': '#fcf9f3',
        'tertiary-container': '#b4b2b2',
        'outline-variant': '#d0c5af',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#ffe08b',
        'on-primary-fixed': '#241a00',
        'secondary-fixed': '#e9e2d3',
        'on-primary-container': '#564300',
        'secondary-fixed-dim': '#cdc6b8',
        'surface-dim': '#dcdad4',
        'on-tertiary-fixed': '#1b1c1c',
        'surface-tint': '#745b00',
        'on-tertiary-fixed-variant': '#474747',
        'primary-fixed-dim': '#eac249',
        'on-background': '#1c1c18',
        'secondary': '#635e53',
        'on-primary-fixed-variant': '#584400',
        'primary-container': '#d5af37',
        'surface-container-highest': '#e5e2dc',
        'on-surface': '#1c1c18',
        'on-secondary-fixed': '#1e1b13',
        'primary': '#745b00',
        'surface-container': '#f0eee8',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-primary': '#eac249',
        'on-surface-variant': '#4d4635',
        'surface-container-high': '#ebe8e2',
        'tertiary': '#5f5e5e',
        'surface': '#fcf9f3',
        'surface-variant': '#e5e2dc',
        'secondary-container': '#e9e2d3',
        'inverse-surface': '#31312d',
        'inverse-on-surface': '#f3f0ea',
        'on-tertiary-container': '#454545',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'background': '#fcf9f3',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#696458',
        'surface-container-low': '#f6f3ed',
        'outline': '#7f7663',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
